# Site settings
title: Baumkosmus
email: info@baumkosmos.de
description: > # this means to ignore newlines until "baseurl:"
Im Rahmen unseres Arboristikbetriebs "Baumkosmos" bieten wir unter anderem folgende Leistungen: Baumkontrolle, Totholzentfernung, Kronenpflege, Fassadenfreischnitt, Lichtraumschnitt, Kronensicherung, Kronenreduktion, und Fällung.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://baumkosmos.de" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
